---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: oauth-dev
  namespace: wish-micro
  annotations:
    fluxcd.io/automated: "true"
    flux.weave.works/automated: "true"
    filter.fluxcd.io/chart-image: semver:~0.0
spec:
  releaseName: oauth-dev
  chart:
    git: git@github.com:yikaitang-wish/helm-operator-get-started
    path: charts/oauth
    ref: master
  values:
    image:
      repository: 030836370731.dkr.ecr.cn-north-1.amazonaws.com.cn/micro_fe/oauth/dev-yikai
      tag: 0.0.1
    replicaCount: 1

